name: CI

on:
    pull_request:
        branches: ['master', 'stable']
    push:
        branches: ['master', 'stable']

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: '12'
                check-latest: true
          - name: Install Dependencies
            run: yarn install --frozen-lockfile --check-files
          - uses: actions/cache@v2
            id: cache-build
            with:
                path: ./*
                key: ${{ github.sha }}

    lint:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/cache@v2
              id: restore-build
              with:
                  path: ./*
                  key: ${{ github.sha }}
            - name: Lint
              run: yarn lint
            - name: Format
              run: yarn format:check